set echo on
spool VPD_USER.log
DROP USER VPD_TEST CASCADE;
-- USER SQL
CREATE USER VPD_TEST IDENTIFIED BY "oracle"  
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER VPD_TEST QUOTA UNLIMITED ON USERS;

-- ROLES
GRANT "CONNECT" TO VPD_TEST;

-- SYSTEM PRIVILEGES
GRANT CREATE TRIGGER TO VPD_TEST;
GRANT CREATE MATERIALIZED VIEW TO VPD_TEST;
GRANT CREATE VIEW TO VPD_TEST;
GRANT CREATE SESSION TO VPD_TEST;
GRANT CREATE TABLE TO VPD_TEST;
GRANT CREATE PUBLIC SYNONYM TO VPD_TEST;
GRANT DROP PUBLIC SYNONYM TO VPD_TEST;
GRANT CREATE SYNONYM TO VPD_TEST;
grant create sequence to vpd_test;
GRANT CREATE PROCEDURE TO VPD_TEST;
GRANT CREATE ANY CONTEXT TO VPD_TEST;
GRANT DROP ANY CONTEXT TO VPD_TEST;
GRANT EXECUTE ON DBMS_RLS TO vpd_test;
spool off;
